<template>
  <section class="subscription-card">
    <div v-if="loading" class="state-box">
      Loading subscription information...
    </div>

    <div v-else>
      <div v-if="error" class="alert alert-error">
        {{ error }}
      </div>

      <div v-if="success" class="alert alert-success">
        {{ success }}
      </div>

      <div class="header-row">
        <div>
          <p class="eyebrow">Subscription & Billing</p>
          <h2 class="card-title">{{ planName }}</h2>
          <p class="card-subtitle">
            {{ billingCycle }} • {{ termLabel }}
          </p>
        </div>

        <div class="header-badges">
          <span class="badge" :class="paymentBadgeClass">
            {{ displayPaymentStatus }}
          </span>

          <span class="badge" :class="statusBadgeClass">
            {{ currentStatus }}
          </span>
        </div>
      </div>

      <!-- Hero summary -->
      <div class="hero-panel">
        <div class="hero-left">
          <p class="hero-label">Current term invoice</p>

          <div class="hero-amount">
            ₵{{ formattedTotalAmount }}
          </div>

          <p class="hero-note">
            Based on <strong>{{ studentsBilled }}</strong> billed students at
            <strong>₵{{ formattedPrice }}</strong> per student.
          </p>
        </div>

        <div class="hero-right">
          <div class="renewal-box">
            <span class="renewal-label">Payment Deadline</span>
            <span class="renewal-date">{{ dueDate }}</span>
          </div>
        </div>
      </div>

      <!-- Metrics -->
      <div class="stats-grid">
        <div class="stat-item">
          <div class="stat-icon icon-blue">₵</div>
          <div>
            <p class="stat-label">Price Per Student</p>
            <p class="stat-value">₵{{ formattedPrice }}</p>
          </div>
        </div>

        <div class="stat-item">
          <div class="stat-icon icon-indigo">👥</div>
          <div>
            <p class="stat-label">Students Billed</p>
            <p class="stat-value">{{ studentsBilled }}</p>
          </div>
        </div>

        <div class="stat-item">
          <div class="stat-icon icon-sky">📅</div>
          <div>
            <p class="stat-label">Payment Deadline</p>
            <p class="stat-value">{{ dueDate }}</p>
          </div>
        </div>

        <div class="stat-item">
          <div class="stat-icon icon-emerald">✓</div>
          <div>
            <p class="stat-label">Invoice Status</p>
            <p class="stat-value">{{ displayPaymentStatus }}</p>
          </div>
        </div>
      </div>

      <!-- Footer actions -->
      <div class="card-footer">
        <div class="footer-info">
          <p class="footer-title">Current term billing</p>
          <!-- <p class="footer-text">
            This card checks invoices generated by the backend using the tenant code
            stored in local storage.
          </p> -->
        </div>

        <div class="footer-actions">
          <button class="btn btn-secondary" type="button" @click="fetchBilling()">
            Refresh
          </button>

          <button
            class="btn btn-primary"
            type="button"
            :disabled="!canMakePayment || paying || verifying"
            @click="makePayment"
          >
            {{ buttonLabel }}
          </button>
        </div>
      </div>

      <!-- Invoice history -->
      <div class="invoice-section">
        <div class="invoice-header">
          <div>
            <h3>Invoices</h3>
            <p>All invoices linked to this tenant.</p>
          </div>

          <span class="invoice-count">
            {{ invoices.length }} invoice(s)
          </span>
        </div>

        <div v-if="invoices.length === 0" class="empty-invoices">
          No invoices found yet.
        </div>

        <div v-else class="invoice-list">
          <div
            v-for="invoice in invoices"
            :key="invoice.invoiceId"
            class="invoice-item"
            :class="{ active: currentInvoice && invoice.invoiceId === currentInvoice.invoiceId }"
          >
            <div>
              <strong>{{ invoice.academicYearName }} • {{ invoice.termName }}</strong>
              <span>
                {{ invoice.studentCount }} students × ₵{{ formatMoney(invoice.amountPerStudentCedis) }}
              </span>
              <small>Due: {{ formatDate(invoice.dueDateEpochMillis) }}</small>
            </div>

            <div class="invoice-right">
              <strong>₵{{ formatMoney(invoice.totalAmountCedis) }}</strong>
              <span class="mini-badge" :class="invoiceStatusClass(invoice.paymentStatus)">
                {{ formatStatus(invoice.paymentStatus) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import {
    getInvoices,
    initializePaystackPayment,
    verifyPaystackPayment,
} from '@/adminBox/services/billingApi.js'

import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'

const props = defineProps({
  planName: {
    type: String,
    default: 'Standard Plan',
  },
  billingCycle: {
    type: String,
    default: 'Billed Per Term',
  },
  pollIntervalMs: {
    type: Number,
    default: 30000,
  },
})

const route = useRoute()

const loading = ref(false)
const paying = ref(false)
const verifying = ref(false)
const error = ref('')
const success = ref('')
const invoices = ref([])
const pollTimer = ref(null)

// const paystackPublicKey = import.meta.env.VITE_PAYSTACK_PUBLIC_KEY
// const paystackPublicKey = "pk_test_2fa7e7b672eb476a4681c757923ea7fcbdff047f"
const paystackPublicKey = "pk_live_851550690ca2d39b76b6fadacf0a760db6adf652"






const resolvedTenantCode = computed(() => {
  return (
    localStorage.getItem('tenantCode') ||
    localStorage.getItem('tenant_code') ||
    ''
  )
})

const payerEmail = computed(() => {
  return (
    localStorage.getItem('email') ||
    localStorage.getItem('accountEmail') ||
    localStorage.getItem('userEmail') ||
    localStorage.getItem('superadmin_email') ||
    ''
  )
})

const currentInvoice = computed(() => {
  if (!invoices.value.length) return null

  return [...invoices.value].sort((a, b) => {
    return Number(b.createdAtEpochMillis || 0) - Number(a.createdAtEpochMillis || 0)
  })[0]
})

const paymentStatus = computed(() => {
  return currentInvoice.value?.paymentStatus || 'unknown'
})

const displayPaymentStatus = computed(() => {
  return formatStatus(paymentStatus.value)
})

const isPaid = computed(() => {
  return Boolean(currentInvoice.value?.isPaid) || paymentStatus.value === 'paid'
})

const canMakePayment = computed(() => {
  const invoice = currentInvoice.value

  if (!invoice) return false

  return (
    ['pending', 'overdue'].includes(String(invoice.paymentStatus || '').toLowerCase()) &&
    !invoice.isPaid &&
    !paying.value &&
    !verifying.value
  )
})

const currentStatus = computed(() => {
  if (!currentInvoice.value) return 'Unknown'

  if (paymentStatus.value === 'free_trial') return 'Trial'
  if (paymentStatus.value === 'paid') return 'Active'
  if (paymentStatus.value === 'overdue') return 'Suspended'
  if (paymentStatus.value === 'pending') return 'Pending'

  return 'Unknown'
})

const paymentBadgeClass = computed(() => {
  return invoiceStatusClass(paymentStatus.value)
})

const statusBadgeClass = computed(() => {
  switch (currentStatus.value.toLowerCase()) {
    case 'active':
      return 'bg-blue-50 text-blue-700 border border-blue-200'
    case 'trial':
      return 'bg-violet-50 text-violet-700 border border-violet-200'
    case 'suspended':
      return 'bg-red-50 text-red-700 border border-red-200'
    case 'pending':
      return 'bg-amber-50 text-amber-700 border border-amber-200'
    default:
      return 'bg-gray-50 text-gray-700 border border-gray-200'
  }
})

const formattedTotalAmount = computed(() => {
  return formatMoney(currentInvoice.value?.totalAmountCedis || 0)
})

const formattedPrice = computed(() => {
  return formatMoney(currentInvoice.value?.amountPerStudentCedis || 5)
})

const studentsBilled = computed(() => {
  return Number(currentInvoice.value?.studentCount || 0).toLocaleString()
})

const termLabel = computed(() => {
  if (!currentInvoice.value) return '-'

  return `${currentInvoice.value.academicYearName || ''} • ${currentInvoice.value.termName || ''}`
})

const dueDate = computed(() => {
  return formatDate(currentInvoice.value?.dueDateEpochMillis)
})

const buttonLabel = computed(() => {
  if (paying.value) return 'Opening Paystack...'
  if (verifying.value) return 'Verifying...'
  if (!currentInvoice.value) return 'No Invoice'
  if (isPaid.value) return 'Paid'

  if (paymentStatus.value === 'free_trial') return 'Free Trial Active'
  if (paymentStatus.value === 'overdue') return 'Pay Now To Reactivate'
  if (paymentStatus.value === 'pending') return 'Make Payment'

  return 'Unavailable'
})

function formatMoney(value) {
  const amount = Number(value || 0)

  return new Intl.NumberFormat('en-GH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount)
}

function formatDate(epochMillis) {
  if (!epochMillis) return '-'

  return new Date(Number(epochMillis)).toLocaleDateString('en-GH', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

function formatStatus(status) {
  return String(status || 'unknown').replaceAll('_', ' ')
}

function invoiceStatusClass(status) {
  switch (String(status || '').toLowerCase()) {
    case 'paid':
      return 'bg-emerald-50 text-emerald-700 border border-emerald-200'
    case 'pending':
      return 'bg-amber-50 text-amber-700 border border-amber-200'
    case 'overdue':
      return 'bg-red-50 text-red-700 border border-red-200'
    case 'free_trial':
      return 'bg-violet-50 text-violet-700 border border-violet-200'
    default:
      return 'bg-gray-50 text-gray-700 border border-gray-200'
  }
}



async function fetchBilling(options = {}) {
  const { silent = false } = options

  if (!resolvedTenantCode.value) {
    error.value = 'Tenant code not found. Please login again.'
    return
  }

  if (!silent) {
    loading.value = true
  }

  error.value = ''

  try {
    const response = await getInvoices({
      tenantCode: resolvedTenantCode.value,
    })

    invoices.value = Array.isArray(response.data) ? response.data : []
  } catch (err) {
    error.value =
      err.response?.data?.message ||
      err.response?.data?.error ||
      err.message ||
      'Unable to load invoice information.'
  } finally {
    loading.value = false
  }
}

async function makePayment() {
  const invoice = currentInvoice.value

  if (!invoice?.invoiceId) {
    error.value = 'No invoice found for payment.'
    return
  }

  if (!canMakePayment.value) return

//   const publicKey = import.meta.env.VITE_PAYSTACK_PUBLIC_KEY

const publicKey = "pk_live_851550690ca2d39b76b6fadacf0a760db6adf652"



  if (!publicKey) {
    error.value = 'Paystack public key is missing. Add VITE_PAYSTACK_PUBLIC_KEY to your .env file.'
    return
  }

  const email =
    localStorage.getItem('email') ||
    localStorage.getItem('accountEmail') ||
    localStorage.getItem('userEmail') ||
    ''

  if (!email) {
    error.value = 'Email address is missing. Please login again.'
    return
  }

  const amountForPaystack = Math.round(Number(invoice.totalAmountCedis || 0) * 100)

  if (amountForPaystack <= 0) {
    error.value = 'Invoice amount must be greater than ₵0.00 before payment.'
    return
  }

  paying.value = true
  error.value = ''
  success.value = ''

  try {
    const initResponse = await initializePaystackPayment(invoice.invoiceId)

    const reference =
      initResponse.data?.reference ||
      initResponse.data?.paystackReference ||
      invoice.paystackReference

    if (!reference) {
      throw new Error('Payment reference was not returned.')
    }

    await loadPaystackInlineScript()

    if (!window.PaystackPop) {
      throw new Error('Paystack popup could not be loaded.')
    }

    const handler = window.PaystackPop.setup({
      key: publicKey,
      email,
      amount: amountForPaystack,
      currency: 'GHS',
      ref: reference,

      callback: function (response) {
        const verifiedReference = response?.reference || reference

        verifyPaymentByReference(verifiedReference)
      },

      onClose: function () {
        paying.value = false
      },
    })

    handler.openIframe()
  } catch (err) {
    error.value =
      err.response?.data?.message ||
      err.response?.data?.error ||
      err.message ||
      'Unable to initialize payment.'

    paying.value = false
  }
}


function loadPaystackInlineScript() {
  return new Promise((resolve, reject) => {
    if (window.PaystackPop) {
      resolve()
      return
    }

    const existingScript = document.querySelector(
      'script[src="https://js.paystack.co/v1/inline.js"]'
    )

    if (existingScript) {
      existingScript.addEventListener('load', resolve)
      existingScript.addEventListener('error', reject)
      return
    }

    const script = document.createElement('script')
    script.src = 'https://js.paystack.co/v1/inline.js'
    script.async = true
    script.onload = resolve
    script.onerror = reject

    document.head.appendChild(script)
  })
}




async function verifyPaymentByReference(reference) {
  if (!reference) return

  verifying.value = true
  paying.value = false
  error.value = ''
  success.value = ''

  try {
    const response = await verifyPaystackPayment(reference)

    if (response.data?.success) {
      success.value = 'Payment verified successfully.'
    } else {
      error.value = response.data?.message || 'Payment could not be verified.'
    }

    await fetchBilling({ silent: true })
  } finally {
    verifying.value = false
  }
}

async function verifyFromCallbackIfNeeded() {
  const reference =
    route.query.reference ||
    route.query.trxref ||
    localStorage.getItem('lastPaystackReference')

  if (!reference) return

  await verifyPaymentByReference(reference)

  localStorage.removeItem('lastPaystackReference')
}

function startPolling() {
  stopPolling()

  pollTimer.value = window.setInterval(() => {
    fetchBilling({ silent: true })
  }, props.pollIntervalMs)
}

function stopPolling() {
  if (pollTimer.value) {
    clearInterval(pollTimer.value)
    pollTimer.value = null
  }
}

onMounted(async () => {
  await verifyFromCallbackIfNeeded()
  await fetchBilling()
  startPolling()
})

onBeforeUnmount(() => {
  stopPolling()
})
</script>



<style scoped>
.subscription-card {
  background: linear-gradient(180deg, #ffffff 0%, #fbfdff 100%);
  border: 1px solid #e5e7eb;
  border-radius: 28px;
  padding: 1.5rem;
  box-shadow:
    0 12px 30px rgba(15, 23, 42, 0.06),
    0 2px 8px rgba(15, 23, 42, 0.03);
}

.state-box {
  padding: 1.2rem;
  border-radius: 18px;
  background: #f8fafc;
  color: #0f172a;
  font-weight: 800;
}

.alert {
  padding: 0.9rem 1rem;
  border-radius: 16px;
  margin-bottom: 1rem;
  font-weight: 800;
}

.alert-error {
  background: #fee2e2;
  color: #991b1b;
  border: 1px solid #fecaca;
}

.alert-success {
  background: #dcfce7;
  color: #166534;
  border: 1px solid #bbf7d0;
}

.header-row {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: flex-start;
  margin-bottom: 1.25rem;
  flex-wrap: wrap;
}

.eyebrow {
  font-size: 0.8rem;
  font-weight: 700;
  color: #64748b;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  margin-bottom: 0.35rem;
}

.card-title {
  font-size: 1.5rem;
  line-height: 1.2;
  font-weight: 800;
  color: #0f172a;
  margin: 0;
}

.card-subtitle {
  margin-top: 0.35rem;
  font-size: 0.95rem;
  color: #64748b;
}

.header-badges {
  display: flex;
  gap: 0.65rem;
  flex-wrap: wrap;
}

.badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 36px;
  padding: 0.45rem 0.85rem;
  border-radius: 999px;
  font-size: 0.84rem;
  font-weight: 800;
  white-space: nowrap;
  text-transform: capitalize;
}

.hero-panel {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: stretch;
  background: linear-gradient(135deg, #eff6ff 0%, #f8fbff 100%);
  border: 1px solid #dbeafe;
  border-radius: 22px;
  padding: 1.2rem;
  margin-bottom: 1.25rem;
  flex-wrap: wrap;
}

.hero-left {
  flex: 1 1 320px;
}

.hero-label {
  font-size: 0.85rem;
  font-weight: 700;
  color: #475569;
  margin-bottom: 0.4rem;
}

.hero-amount {
  font-size: 2rem;
  font-weight: 900;
  letter-spacing: -0.03em;
  color: #0f172a;
  margin-bottom: 0.3rem;
}

.hero-note {
  color: #64748b;
  font-size: 0.92rem;
  line-height: 1.5;
}

.hero-note strong {
  color: #0f172a;
}

.hero-right {
  display: flex;
  align-items: center;
}

.renewal-box {
  min-width: 190px;
  background: #ffffff;
  border: 1px solid #dbeafe;
  border-radius: 18px;
  padding: 0.9rem 1rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.06);
}

.renewal-label {
  font-size: 0.76rem;
  font-weight: 800;
  text-transform: uppercase;
  color: #64748b;
  letter-spacing: 0.06em;
  margin-bottom: 0.3rem;
}

.renewal-date {
  font-size: 1rem;
  font-weight: 800;
  color: #0f172a;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.95rem;
  margin-bottom: 1.25rem;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 0.9rem;
  border: 1px solid #e5e7eb;
  background: #ffffff;
  border-radius: 20px;
  padding: 1rem;
}

.stat-icon {
  width: 42px;
  height: 42px;
  border-radius: 14px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  font-weight: 900;
}

.icon-blue {
  background: #eff6ff;
  color: #2563eb;
}

.icon-indigo {
  background: #eef2ff;
  color: #4f46e5;
}

.icon-sky {
  background: #f0f9ff;
  color: #0284c7;
}

.icon-emerald {
  background: #ecfdf5;
  color: #059669;
}

.stat-label {
  font-size: 0.8rem;
  color: #64748b;
  font-weight: 700;
  margin-bottom: 0.2rem;
}

.stat-value {
  font-size: 1.02rem;
  color: #0f172a;
  font-weight: 800;
  text-transform: capitalize;
}

.card-footer {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: center;
  padding-top: 0.3rem;
  flex-wrap: wrap;
}

.footer-info {
  flex: 1 1 260px;
}

.footer-title {
  font-size: 0.98rem;
  font-weight: 800;
  color: #0f172a;
  margin-bottom: 0.25rem;
}

.footer-text {
  font-size: 0.9rem;
  line-height: 1.5;
  color: #64748b;
}

.footer-actions {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
}

.btn {
  min-height: 44px;
  border-radius: 14px;
  padding: 0 1rem;
  font-size: 0.92rem;
  font-weight: 800;
  transition: all 0.2s ease;
  cursor: pointer;
  border: none;
}

.btn:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.btn-secondary {
  background: #ffffff;
  color: #0f172a;
  border: 1px solid #d1d5db;
}

.btn-secondary:hover {
  background: #f8fafc;
}

.btn-primary {
  background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
  color: #ffffff;
  box-shadow: 0 8px 18px rgba(37, 99, 235, 0.18);
}

.btn-primary:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 12px 24px rgba(37, 99, 235, 0.22);
}

.invoice-section {
  margin-top: 1.4rem;
  border-top: 1px solid #e5e7eb;
  padding-top: 1.2rem;
}

.invoice-header {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  margin-bottom: 1rem;
  align-items: flex-start;
}

.invoice-header h3 {
  margin: 0;
  font-size: 1rem;
  font-weight: 800;
  color: #0f172a;
}

.invoice-header p {
  margin: 0.25rem 0 0;
  color: #64748b;
  font-size: 0.88rem;
}

.invoice-count {
  display: inline-flex;
  padding: 0.45rem 0.75rem;
  border-radius: 999px;
  background: #f1f5f9;
  color: #334155;
  font-weight: 800;
  font-size: 0.8rem;
}

.empty-invoices {
  padding: 1rem;
  border-radius: 16px;
  background: #f8fafc;
  color: #64748b;
  font-weight: 700;
}

.invoice-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.invoice-item {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  padding: 1rem;
  border-radius: 18px;
  border: 1px solid #e5e7eb;
  background: #ffffff;
}

.invoice-item.active {
  border-color: #2563eb;
  background: #eff6ff;
}

.invoice-item strong {
  display: block;
  color: #0f172a;
  font-weight: 800;
}

.invoice-item span,
.invoice-item small {
  display: block;
  color: #64748b;
  margin-top: 0.2rem;
  font-size: 0.85rem;
}

.invoice-right {
  text-align: right;
  min-width: 120px;
}

.mini-badge {
  display: inline-flex;
  margin-top: 0.35rem;
  padding: 0.35rem 0.65rem;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 800;
  text-transform: capitalize;
}

.bg-blue-50 {
  background: #eff6ff;
}

.text-blue-700 {
  color: #1d4ed8;
}

.border-blue-200 {
  border-color: #bfdbfe;
}

.bg-violet-50 {
  background: #f5f3ff;
}

.text-violet-700 {
  color: #6d28d9;
}

.border-violet-200 {
  border-color: #ddd6fe;
}

.bg-red-50 {
  background: #fef2f2;
}

.text-red-700 {
  color: #b91c1c;
}

.border-red-200 {
  border-color: #fecaca;
}

.bg-amber-50 {
  background: #fffbeb;
}

.text-amber-700 {
  color: #b45309;
}

.border-amber-200 {
  border-color: #fde68a;
}

.bg-emerald-50 {
  background: #ecfdf5;
}

.text-emerald-700 {
  color: #047857;
}

.border-emerald-200 {
  border-color: #a7f3d0;
}

.bg-gray-50 {
  background: #f9fafb;
}

.text-gray-700 {
  color: #374151;
}

.border-gray-200 {
  border-color: #e5e7eb;
}

.border {
  border-width: 1px;
  border-style: solid;
}

@media (max-width: 768px) {
  .stats-grid {
    grid-template-columns: 1fr;
  }

  .hero-amount {
    font-size: 1.7rem;
  }

  .subscription-card {
    padding: 1.15rem;
  }

  .card-footer {
    align-items: stretch;
  }

  .footer-actions {
    width: 100%;
  }

  .btn {
    flex: 1;
  }

  .invoice-item,
  .invoice-header {
    flex-direction: column;
  }

  .invoice-right {
    text-align: left;
  }
}
</style>
